### PR TITLE
Fix oversized icons and invisible button in admin panel

### LINKED ISSUE #184: [Bug] Invisible button in admin panel
### Expected Behavior

Button is invisible

### Steps to Reproduce

image

### Device Information

Desktop/Mobile: Desktop
OS: macOS Monterey 12.3.1
Browser Version: Safari 15.4

### LINKED ISSUE #185: [Bug] ProfileBox icons are oversized
### Expected Behavior

ProfileBox icons are oversized. Change to make them smaller

### Steps to Reproduce

image

### Device Information

Desktop/Mobile: Desktop
OS: macOS Monterey 12.3.1
Browser Version: Safari 15.4

### PR DESCRIPTION
**Pull request by gramliu**
# Description

Closes #184 
Closes #185

image
image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Node.js version:
- Python version:
- Desktop/Mobile:
- OS:
- Browser:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/components/admin/ParticipantTable/index.tsx [hunk 1]
```diff
@@ -320,6 +318,7 @@ const ParticipantTable = (): ReactElement => {
           <div className={styles.toolbarContent}>
             <RectangleButton
               type="button"
+              disabled
```
Comment (pm3512) [inline src/components/admin/ParticipantTable/index.tsx:321]: Are the buttons enabled at some point or do we always want them disabled?

Comment (gramliu) [reply src/components/admin/ParticipantTable/index.tsx:321]: We might re-enable them in the future, but I'm temporarily disabling them this cycle since after looking at the applications, we might actually need to evaluate them more closely this year. Despite the big disclaimers, some grad students still applied lol

**Review by pm3512 — APPROVED** [review]
